### PR TITLE
IPTables: add chain abstraction

### PR DESCRIPTION
**Pull request by oliviertilmans**
Add QoL chain helper to more easily express rules.

I do not have a proper ipmininet install at disposal at the moment, I've likely botched this...

### CODE REVIEW

**Comment by oliviertilmans** [comment]
I wanted to stress that NOT was a DSL element and not a python object. Arguably Deny/Allow/transitfiltrr/... Also should be in uppercase (i.e. all terminal constructs).

In the case of NOT this seemed particularly necessary to be as different as possible from the python not built-in...which unfortunately cannot be overloaded through magic methods.

**Comment by jadinm** [comment]
Ok, let's keep "NOT" as it is
I think that's a good idea all things considered

**Comment by jadinm** [comment]
Jenkins, run tests.

**Comment by jadinm** [comment]
Jenkins, rerun tests.

**Comment by jadinm** [comment]
Jenkins, rerun tests.

**Comment by jadinm** [comment]
Jenkins, rerun tests.

**Pull request merged**
