### PR TITLE
Add jenkins

### PR DESCRIPTION
**Pull request by jadinm**
I set up a jenkins instance that will test the new PRs and the current master branch.

To trigger tests autmatically, there are two hooks that an admin of the repository needs to add:

 - One to https://jenkins-mininet.info.ucl.ac.be/github-webhook/ that is triggered at ``Pushes``
 - A second one to https://jenkins-mininet.info.ucl.ac.be/ghprbhook/ that is triggered at ``Pull Requests``

### CODE REVIEW

**Comment by butjar** [comment]
Did you consider using [travis](https://travis-ci.org/)? Would give more transparency to the CI.

**Comment by jadinm** [comment]
> Did you consider using [travis](https://travis-ci.org/)? Would give more transparency to the CI.

I did not really have the choice ^^
We need sudo access for tests, so we need a seperate server and the sysadmins here prefer jenkins.

**Comment by butjar** [comment]
> I did not really have the choice ^^
> We need sudo access for tests, so we need a seperate server and the sysadmins here prefer jenkins.

Travis is a managed service which is free for open source. Transparency of the builds would be a plus, I guess. Maybe I can find time to look into it and create a PR if you are interested.

**Comment by jadinm** [comment]
I do not understand what transparency it would add.
All the build logs are in https://jenkins-mininet.info.ucl.ac.be/job/ipmininet/, no ?

**Comment by butjar** [comment]
> I do not understand what transparency it would add.
> All the build logs are in https://jenkins-mininet.info.ucl.ac.be/job/ipmininet/, no ?

Yes exactly, cool.

**Comment by oliviertilmans** [comment]
@jadinm due to the transfert to the cnp3 org, I no longer have admin access to this repo (or all the others I transferred). You should check with @obonaventure whether he can grant you more than write access on this repo.

**Pull request merged**
